version: '2'
services:
  portainer-prod:
    #    image: portainer:latest
    #image: portainer/update:latest
    image: lcr.loongnix.cn/portainer/portainer:2.11.1
    container_name: portainer-prod
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:

